// <auto-generated />
using System;
using Car_Rental.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car_Rental.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    [Migration("20210419135730_DropedColumnAPrice")]
    partial class DropedColumnAPrice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Car_Rental.Models.Address", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Street_Number")
                        .HasColumnType("int");

                    b.Property<string>("Zip_Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer_ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Car_Rental.Models.BlackList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ban_Time")
                        .HasColumnType("int");

                    b.Property<string>("Cauza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BlackLists");
                });

            modelBuilder.Entity("Car_Rental.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Acceleration")
                        .HasColumnType("real");

                    b.Property<float>("AverageScore")
                        .HasColumnType("real");

                    b.Property<string>("Category_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ClimateControll")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fabrication_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransmisionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type_ID")
                        .HasColumnType("int");

                    b.HasKey("CarID");

                    b.HasIndex("Category_Name");

                    b.HasIndex("Type_ID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Car_Rental.Models.CarCategory", b =>
                {
                    b.Property<string>("Category_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCars")
                        .HasColumnType("int");

                    b.HasKey("Category_Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Car_Rental.Models.CarLocation", b =>
                {
                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.HasKey("CarID", "LocationID");

                    b.HasIndex("LocationID");

                    b.ToTable("CarLocation");
                });

            modelBuilder.Entity("Car_Rental.Models.CarTypes", b =>
                {
                    b.Property<int>("Type_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number_Doors")
                        .HasColumnType("int");

                    b.Property<int>("Number_Passengers")
                        .HasColumnType("int");

                    b.Property<int>("Number_Suitacases")
                        .HasColumnType("int");

                    b.HasKey("Type_ID");

                    b.ToTable("CarTypes");
                });

            modelBuilder.Entity("Car_Rental.Models.Coupon", b =>
                {
                    b.Property<int>("Coupon_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Coupon_ID");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Car_Rental.Models.Customer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BlackListID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role_ID")
                        .HasColumnType("int");

                    b.Property<string>("Second_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer_ID");

                    b.HasIndex("BlackListID");

                    b.HasIndex("Role_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Car_Rental.Models.Location", b =>
                {
                    b.Property<int>("Location_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Street_Numver")
                        .HasColumnType("int");

                    b.HasKey("Location_ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Car_Rental.Models.Reservation", b =>
                {
                    b.Property<int>("Reservation_ID")
                        .HasColumnType("int");

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<int?>("Coupon_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status_ID")
                        .HasColumnType("int");

                    b.HasKey("Reservation_ID");

                    b.HasIndex("CarID");

                    b.HasIndex("Coupon_ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Status_ID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Car_Rental.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Car_Rental.Models.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Car_Rental.Models.Status", b =>
                {
                    b.Property<int>("Status_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Status_ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Car_Rental.Models.Car", b =>
                {
                    b.HasOne("Car_Rental.Models.CarCategory", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("Category_Name");

                    b.HasOne("Car_Rental.Models.CarTypes", "Type")
                        .WithMany("Cars")
                        .HasForeignKey("Type_ID");
                });

            modelBuilder.Entity("Car_Rental.Models.CarLocation", b =>
                {
                    b.HasOne("Car_Rental.Models.Car", "Car")
                        .WithMany("CarLocations")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Rental.Models.Location", "Location")
                        .WithMany("CarsAtLocation")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Car_Rental.Models.Customer", b =>
                {
                    b.HasOne("Car_Rental.Models.BlackList", "BlackList")
                        .WithMany("Customers")
                        .HasForeignKey("BlackListID");

                    b.HasOne("Car_Rental.Models.Address", "Address")
                        .WithOne("Customer")
                        .HasForeignKey("Car_Rental.Models.Customer", "Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Rental.Models.Role", "Role")
                        .WithMany("Customers")
                        .HasForeignKey("Role_ID");
                });

            modelBuilder.Entity("Car_Rental.Models.Reservation", b =>
                {
                    b.HasOne("Car_Rental.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarID");

                    b.HasOne("Car_Rental.Models.Coupon", "Coupon")
                        .WithMany("Reservaions")
                        .HasForeignKey("Coupon_ID");

                    b.HasOne("Car_Rental.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("Customer_ID");

                    b.HasOne("Car_Rental.Models.Review", "Review")
                        .WithOne("Reservation")
                        .HasForeignKey("Car_Rental.Models.Reservation", "Reservation_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Rental.Models.Status", "Status")
                        .WithMany("Reservations")
                        .HasForeignKey("Status_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
